In [83]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import math

C:\Anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [84]:
dataset_path = 'C:\\Users\\DWQE\\LinuxFiles\\MachineLearning2020\\PersonalProject\\Dataset\\'
df = pd.read_csv(dataset_path + 'train_ngk.csv')

In [85]:
X, y = df.iloc[:, :-2].values, df.iloc[:, -1].values

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [87]:
regression = RandomForestRegressor(criterion='mae')
regression.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [88]:
y_pred = regression.predict(X_test)
print(r2_score(y_test, y_pred))

0.9793933116169438


In [89]:
y_test

array([3.09104245, 6.68461173, 4.31748811, ..., 3.48124009, 4.2121276 ,
       4.49980967])

In [90]:
e_y_test = np.exp(y_test)

In [91]:
e_y_pred = np.exp(y_pred)

In [92]:
e_y_test

array([ 22. , 800. ,  75. , ...,  32.5,  67.5,  90. ])

In [93]:
e_y_pred

array([ 28.94920139, 817.04223963,  72.6942293 , ...,  40.67177333,
        66.1109851 ,  87.91154195])

In [94]:
minus = e_y_test - e_y_pred

In [95]:
mae = list(np.maximum(minus,  -minus))

In [96]:
mae.sort()

In [97]:
sum(mae) / len(mae)

33.15801530612938